version: "3.5"
services:
  nethermind:
    build:
      context: .
      args:
        UPSTREAM_VERSION: 1.14.5
    image: "nethermind.chiado-nethermind.dnp.dappnode.eth:1.0.0"
    restart: unless-stopped
    security_opt:
      - "seccomp:unconfined"
    volumes:
      - "data:/data"
    environment:
      MODE: normal
      NETHERMIND_CONFIG: chiado
      NETHERMIND_SYNCCONFIG_FASTSYNC: "true"
      NETHERMIND_JSONRPCCONFIG_ENABLED: "true"
      NETHERMIND_JSONRPCCONFIG_HOST: 0.0.0.0
      NETHERMIND_INITCONFIG_WEBSOCKETSENABLED: "true"
      NETHERMIND_NETWORKCONFIG_DISCOVERYPORT: 32304
      NETHERMIND_NETWORKCONFIG_P2PPORT: 32304
      NETHERMIND_JSONRPCCONFIG_ENGINEHOST: 0.0.0.0
      NETHERMIND_JSONRPCCONFIG_ENGINEPORT: 8551
      NETHERMIND_HEALTHCHECKSCONFIG_UIENABLED: "true"
      EXTRA_OPTS: ""
    ports:
      - "32034:32034/udp"
      - "31309:31309/tcp"
    ulimits:
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          memory: 16384M
volumes:
  data: {}
